version: '3.5'


services:
  ponte_chispas_ad:
    container_name: ponte_chispas_ad
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app/src